### ISSUE TITLE
linter- consistency

### ISSUE THREAD

**Issue by danielbayley** [AtomLinter/atom-linter#8]
Some `linter-`s have dependencies included, others seem to find them ok (I presume via `$PATH`), and others force you to explicitly specify the full path to the binary in the config, and break without that.

I'm not sure if this is the right place for this issue, but is there some way there could be more consistency between all of the `linter-`s, making them more robust?

**Comment by steelbrain** [comment]
@danielbayley They only break without that when you don't have them in `$PATH`, and we try to do it with as much ease as possible. I am not sure if we should remove bundled ones just because there are some who are not bundled.

**Comment by danielbayley** [comment]
Well personally I'd rather they were all bundled if some already are. But the main problem is that a handful don't seem to use `$PATH` at all and consequently break.

**Comment by steelbrain** [comment]
We can not bundle all of them actually, 'cause some of them like eslint are extendable, and some are quite heavy like `hh_client`. If you really want some linters to use a bundled version instead of using global, You might wanna open up an issue over to there repo, also We've been working on the `environment package` that fixes `$PATH` on OSX.

**Comment by danielbayley** [comment]
@steelbrain Cool. I wasn't really bothered about that as much as the last point anyway as that's the one causing problems. Great, where can I check that out?

**Comment by steelbrain** [comment]
https://github.com/atom-community/environment
